# CircleCI configuration for Dockerhub
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:erbium


    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin

      - run:
          name: Build and push Docker image
          command: |
            TAG=0.0.$CIRCLE_BUILD_NUM
            docker build -t tvsjsdock/sails-test:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push tvsjsdock/sails-test:$TAG

    # TODO
    # test:
    # ...