# Node.js & Docker CircleCI configuration file
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:erbium-slim

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests <-- TODO
      #- run: yarn test

      # Install Docker
      - run:
        name: Install Docker client
        command: |
        set -x
        VER="18.06.3-ce"
        curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
        tar -xz -C /tmp -f /tmp/docker-$VER.tgz
        mv /tmp/docker/* /usr/bin

    # build and push Docker image
      - run: |
          TAG=0.0.$CIRCLE_BUILD_NUM
          docker build -t tvsjsdock/sails-test:$TAG .     
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push tvsjsdock/sails-test:$TAG